from flask_babel import _

def get_code(number):
    choises = {
        "00":_("Your transaction was aproved. Please go to the course section and enjoy your training."),
        "01":_("Denied, please refer to the bank"),
        "02":_("Denied, please refer to the bank"),
        "03":_("Invalid Merchant"),
        "04":_("Denied, call to the bank"),
        "05":_("Denied, transaction not accepted"),
        "07":_("Keep Card"),
        "12":_("Invalid Transaction"),
        "13":_("Insufficient funds"),
        "14":_("Invalid Cards"),
        "15":_("Merchant Invalid"),
        "19":_("Please try again"),
        "25":_("Register not found"),
        "30":_("Format Error"),
        "31":_("Credit card not supported"),
        "41":_("Credit card lost"),
        "43":_("Credit card stolen"),
        "51":_("Denied, Insufficient founds"),
        "54":_("Denied, Credit card expired"),
        "57":_("Denied, Transaction not permited"),
        "58":_("Denied, Invalid transaction"),
        "61":_("Denied, Exceeded ammount"),
        "62":_("Denied, Credit card restricted"),
        "62":_("Denied, number of transactions exceeded"),
        "78":_("Invalid account"),
        "85":_("Invalid Transaction"),
        "89":_("Invalid terminal"),
        "91":_("Issuer not available, please try again"),
        "96":_("System Malfunction"),
        "100":_("Aproved"),
        "101":_("Declined - The request is missing one or more fields"),
        "102":_("Declined - One or more fields in the request contains invalid data"),
        "104":_("Declined - The merchantReferenceCode sent with this authorization request matches the merchantReferenceCode of another authorization request that you sent in the last 15 minutes."),
        "110":_("Partial amount was approved"),
        "150":_("Error - General system failure."),
        "151":_("Error - The request was received but there was a server timeout. This error does not include timeouts between the client and the server."),
        "152":_("Error: The request was received, but a service did not finish running in time."),
        "200":_("Soft Decline - The authorization request was approved by the issuing bank but declined by CyberSource because it did not pass the Address Verification Service (AVS) check."),
        "201":_("Decline - The issuing bank has questions about the request. You do not receive an authorization code programmatically, but you might receive one verbally by calling the processor."),
        "202":_("Decline - Expired card. You might also receive this if the expiration date you provided does not match the date the issuing bank has on file. Note: The ccCreditService does not check the expiration date; instead, it passes the request to the payment processor. If the payment processor allows issuance of credits to expired cards, CyberSource does not limit this functionality."),
        "203":_("DO NOT HONOR. Decline - General decline of the card. No other information provided by the issuing bank."),
        "204":_("Decline - Insufficient funds in the account."),
        "205":_("Decline - Stolen or lost card."),
        "207":_("Decline - Issuing bank unavailable."),
        "208":_("Decline - Inactive card or card not authorized for card-not-present transactions."),
        "209":_("Decline - card verification number (CVN) did not match."),
        "210":_("Decline - The card has reached the credit limit."),
        "211":_("Decline - Invalid Card Verification Number (CVN)."),
        "220":_("Decline - Generic Decline."),
        "221":_("Decline - The customer matched an entry on the processor's negative file."),
        "222":_("Decline - customer's account is frozen"),
        "230":_("Soft Decline - The authorization request was approved by the issuing bank but declined by CyberSource because it did not pass the card verification number (CVN) check."),
        "231":_("Decline - Invalid account number"),
        "232":_("Decline - The card type is not accepted by the payment processor."),
        "233":_("Decline - General decline by the processor."),
        "234":_("Decline - There is a problem with your CyberSource merchant configuration."),
        "235":_("Decline - The requested amount exceeds the originally authorized amount. Occurs, for example, if you try to capture an amount larger than the original authorization amount."),
        "236":_("Decline - Processor failure."),
        "237":_("Decline - The authorization has already been reversed."),
        "238":_("Decline - The transaction has already been settled."),
        "239":_("Decline - The requested transaction amount must match the previous transaction amount."),
        "240":_("Decline - The card type sent is invalid or does not correlate with the credit card number."),
        "241":_("Decline - The referenced request id is invalid for all follow-on transactions."),
        "242":_("Decline - The request ID is invalid. You requested a capture, but there is no corresponding, unused authorization record. Occurs if there was not a previously successful authorization request or if the previously successful authorization has already been used in another capture request."),
        "243":_("Decline - The transaction has already been settled or reversed."),
        "246":_("Decline - The capture or credit is not voidable because the capture or credit information has already been submitted to your processor. Or, you requested a void for a type of transaction that cannot be voided."),
        "247":_("Decline - You requested a credit for a capture that was previously voided."),
        "248":_("Decline - The boleto request was declined by your processor."),
        "250":_("Error - The request was received, but there was a timeout at the payment processor."),
        "251":_("Decline - The Pinless Debit card's use frequency or maximum amount per use has been exceeded."),
        "254":_("Decline - Account is prohibited from processing stand-alone refunds"),
        "400":_("Soft Decline - Fraud score exceeds threshold."),
        "450":_("Apartment number missing or not found."),
        "451":_("Insufficient address information."),
        "452":_("House/Box number not found on street."),
        "453":_("Multiple address matches were found."),
        "454":_("P.O. Box identifier not found or out of range."),
        "455":_("Route service identifier not found or out of range."),
        "456":_("Street name not found in Postal code."),
        "457":_("Postal code not found in database."),
        "458":_("Unable to verify or correct address."),
        "459":_("Multiple addres matches were found (international)"),
        "460":_("Address match not found (no reason given)"),
        "461":_("Unsupported character set"),
        "475":_("The cardholder is enrolled in Payer Authentication. Please authenticate the cardholder before continuing with the transaction."),
        "476":_("Encountered a Payer Authentication problem. Payer could not be authenticated."),
        "480":_("The order is marked for review by Decision Manager, please contact soporte@qpaypro.com to review the transaction."),
        "481":_("The order has been rejected by Decision Manager"),
        "520":_("Soft Decline - The authorization request was approved by the issuing bank but declined by CyberSource based on your Smart Authorization settings."),
        "700":_("The customer matched the Denied Parties List"),
        "701":_("Export bill_country/ship_country match"),
        "702":_("Export email_country match"),
        "703":_("Export hostname_country/ip_country match"),
    }
    return choises.get(str(number), 0)
